In [27]:
import numpy as np
box = np.zeros((5,5,5))
cheese = np.zeros((1,5,5)) + 1
r = np.concatenate((box, cheese), axis=0)
r

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [28]:
from copy import deepcopy

class A:
    def __init__(self):
        self.aaa = 1

first = A()
second = deepcopy(first)

first.aaa = 2

print('first has %s but second has %s' % (first.aaa, second.aaa))

first has 2 but second has 1


In [29]:
a = np.arange(16).reshape((4,4))
a * a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [30]:
a = np.array([1,2,3,4,5,6])
a += 1
a

array([2, 3, 4, 5, 6, 7])

In [31]:
np.abs(-3)

3

In [36]:
a = np.array([0,0,1])
b = np.array([0,1,0])
c = np.array([0,2,1]) / np.linalg.norm(np.array([0,2,1]))
a @ c

0.4472135954999579

In [62]:
def cartesian_product(*arrays):
    la = len(arrays)
    dtype = np.result_type(*arrays)
    arr = np.empty([len(a) for a in arrays] + [la], dtype=dtype)
    for i, a in enumerate(np.ix_(*arrays)):
        arr[...,i] = a
    return arr.reshape(-1, la)

a = np.array([1])
b = np.array([3,4,5,6])
c = np.array([7.3,'r'])

cartesian_product(a,c)


one = np.array(range(2))
two = np.array(range(3))

cartesian_product(one,two)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [34]:
arr = a,b,c,a
np.stack(np.meshgrid(*arr), -1).reshape(-1, len(arr))

array([[1, 3, 7, 1],
       [1, 3, 7, 2],
       [2, 3, 7, 1],
       [2, 3, 7, 2],
       [1, 4, 7, 1],
       [1, 4, 7, 2],
       [2, 4, 7, 1],
       [2, 4, 7, 2],
       [1, 5, 7, 1],
       [1, 5, 7, 2],
       [2, 5, 7, 1],
       [2, 5, 7, 2],
       [1, 6, 7, 1],
       [1, 6, 7, 2],
       [2, 6, 7, 1],
       [2, 6, 7, 2]])

In [44]:
aa = np.concatenate((a,a)).reshape(2,3)

np.concatenate((aa, [b]), axis=0)

array([[0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]])

In [86]:
x = np.zeros((4,3))
x[0:2] = np.array([[3,1,1],[2,1,1]])
x

array([[3., 1., 1.],
       [2., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.concatenate((a,a))

array([1, 1])